"""add_world_characters_table

Revision ID: 01f437c7c05d
Revises: 7b9e4a1d2c3f
Create Date: 2026-04-09 08:40:51.776855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f437c7c05d'
down_revision: Union[str, Sequence[str], None] = '7b9e4a1d2c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_characters',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('secret', sa.Text(), nullable=True),
    sa.Column('knowledge', sa.JSON(), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('initial_location', sa.String(length=100), nullable=False),
    sa.Column('playable', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('abilities', sa.JSON(), nullable=False),
    sa.Column('starting_inventory', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_characters_playable'), 'world_characters', ['playable'], unique=False)
    op.create_index(op.f('ix_world_characters_world_id'), 'world_characters', ['world_id'], unique=False)
    op.drop_index(op.f('idx_script_drafts_world_id'), table_name='script_drafts')
    op.add_column('scripts', sa.Column('playable_character_ids', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('worlds', sa.Column('free_playable_character_ids', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worlds', 'free_playable_character_ids')
    op.drop_column('scripts', 'playable_character_ids')
    op.create_index(op.f('idx_script_drafts_world_id'), 'script_drafts', ['world_id'], unique=False)
    op.drop_index(op.f('ix_world_characters_world_id'), table_name='world_characters')
    op.drop_index(op.f('ix_world_characters_playable'), table_name='world_characters')
    op.drop_table('world_characters')
    # ### end Alembic commands ###
