"""initial schema

Revision ID: 045766d633e1
Revises: 
Create Date: 2026-04-08 09:25:32.974129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045766d633e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worlds',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('era', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('estimated_time', sa.String(length=50), nullable=False),
    sa.Column('cover_image', sa.String(length=500), nullable=False),
    sa.Column('base_setting', sa.Text(), nullable=False),
    sa.Column('script_setting', sa.Text(), nullable=True),
    sa.Column('free_setting', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('abilities', sa.JSON(), nullable=False),
    sa.Column('starting_location', sa.String(length=100), nullable=False),
    sa.Column('starting_inventory', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endings',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('ending_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('hard_conditions', sa.JSON(), nullable=True),
    sa.Column('soft_conditions', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('trigger_condition', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('effects', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('npcs',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('secret', sa.Text(), nullable=True),
    sa.Column('knowledge', sa.JSON(), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('initial_location', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('character_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('game_state', sa.JSON(), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('ending_type', sa.String(length=50), nullable=True),
    sa.Column('rounds_played', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_played_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_game_sessions_player_last_played', 'game_sessions', ['player_id', 'last_played_at'], unique=False)
    op.create_index('idx_game_sessions_player_status', 'game_sessions', ['player_id', 'status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('state_snapshot', sa.JSON(), nullable=True),
    sa.Column('is_compressed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_session_compressed', 'messages', ['session_id', 'is_compressed'], unique=False)
    op.create_index('idx_messages_session_created', 'messages', ['session_id', 'created_at'], unique=False)
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_usage_created', 'token_usage', ['created_at'], unique=False)
    op.create_index('idx_token_usage_session', 'token_usage', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_token_usage_session', table_name='token_usage')
    op.drop_index('idx_token_usage_created', table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_index('idx_messages_session_created', table_name='messages')
    op.drop_index('idx_messages_session_compressed', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_game_sessions_player_status', table_name='game_sessions')
    op.drop_index('idx_game_sessions_player_last_played', table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_table('npcs')
    op.drop_table('events')
    op.drop_table('endings')
    op.drop_table('characters')
    op.drop_table('worlds')
    # ### end Alembic commands ###
