"""add scripts table and session fields

Revision ID: 472da503b7df
Revises: 045766d633e1
Create Date: 2026-04-08 15:48:52.287970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472da503b7df'
down_revision: Union[str, Sequence[str], None] = '045766d633e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _matching_foreign_key(
    inspector: sa.Inspector,
    table_name: str,
    constrained_columns: list[str],
    referred_table: str,
    referred_columns: list[str],
) -> dict | None:
    for foreign_key in inspector.get_foreign_keys(table_name):
        if (
            foreign_key.get("constrained_columns") == constrained_columns
            and foreign_key.get("referred_table") == referred_table
            and foreign_key.get("referred_columns") == referred_columns
        ):
            return foreign_key
    return None


def _has_matching_foreign_key(
    inspector: sa.Inspector,
    table_name: str,
    constrained_columns: list[str],
    referred_table: str,
    referred_columns: list[str],
) -> bool:
    return (
        _matching_foreign_key(
            inspector,
            table_name,
            constrained_columns,
            referred_table,
            referred_columns,
        )
        is not None
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if "scripts" not in existing_tables:
        op.create_table(
            'scripts',
            sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
            sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('description', sa.Text(), nullable=False),
            sa.Column('difficulty', sa.SmallInteger(), nullable=False),
            sa.Column('estimated_time', sa.String(length=50), nullable=False),
            sa.Column('events_data', sa.JSON(), nullable=False),
            sa.Column('clues_data', sa.JSON(), nullable=False),
            sa.Column('endings_data', sa.JSON(), nullable=False),
            sa.Column('script_setting', sa.Text(), nullable=False),
            sa.Column('is_published', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    if "game_sessions" in existing_tables:
        existing_columns = {column["name"] for column in inspector.get_columns("game_sessions")}
        needs_fk = not _has_matching_foreign_key(
            inspector,
            "game_sessions",
            ["script_id"],
            "scripts",
            ["id"],
        )

        if (
            {"script_id", "authors_note", "state_snapshot", "last_action_text", "retry_count"}
            - existing_columns
        ) or needs_fk:
            fk_name = "fk_game_sessions_script_id_scripts"
            with op.batch_alter_table('game_sessions', schema=None) as batch_op:
                if "script_id" not in existing_columns:
                    batch_op.add_column(sa.Column('script_id', sa.Uuid(as_uuid=False), nullable=True))
                if "authors_note" not in existing_columns:
                    batch_op.add_column(sa.Column('authors_note', sa.Text(), nullable=True))
                if "state_snapshot" not in existing_columns:
                    batch_op.add_column(sa.Column('state_snapshot', sa.JSON(), nullable=True))
                if "last_action_text" not in existing_columns:
                    batch_op.add_column(sa.Column('last_action_text', sa.Text(), nullable=True))
                if "retry_count" not in existing_columns:
                    batch_op.add_column(
                        sa.Column('retry_count', sa.Integer(), nullable=False, server_default=sa.text('0'))
                    )
                if needs_fk:
                    batch_op.create_foreign_key(
                        fk_name,
                        'scripts',
                        ['script_id'],
                        ['id'],
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if "game_sessions" in existing_tables:
        existing_columns = {column["name"] for column in inspector.get_columns("game_sessions")}
        target_columns = {"retry_count", "last_action_text", "state_snapshot", "authors_note", "script_id"}
        if target_columns & existing_columns:
            with op.batch_alter_table('game_sessions', schema=None, recreate="always") as batch_op:
                if "retry_count" in existing_columns:
                    batch_op.drop_column('retry_count')
                if "last_action_text" in existing_columns:
                    batch_op.drop_column('last_action_text')
                if "state_snapshot" in existing_columns:
                    batch_op.drop_column('state_snapshot')
                if "authors_note" in existing_columns:
                    batch_op.drop_column('authors_note')
                if "script_id" in existing_columns:
                    batch_op.drop_column('script_id')
    if "scripts" in existing_tables:
        op.drop_table('scripts')
    # ### end Alembic commands ###
