"""add script_type to scripts

Revision ID: 5561197da50c
Revises: 9d1a2b3c4d5e
Create Date: 2026-04-14 08:08:18.129854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5561197da50c'
down_revision: Union[str, Sequence[str], None] = '9d1a2b3c4d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_generation_task_events_task_id'), table_name='generation_task_events')
    op.create_index(op.f('ix_generation_task_events_task_id'), 'generation_task_events', ['task_id'], unique=False)
    op.drop_index(op.f('idx_generation_tasks_draft_id'), table_name='generation_tasks')
    op.drop_index(op.f('idx_generation_tasks_status'), table_name='generation_tasks')
    op.create_index(op.f('ix_generation_tasks_draft_id'), 'generation_tasks', ['draft_id'], unique=False)
    op.create_index(op.f('ix_generation_tasks_status'), 'generation_tasks', ['status'], unique=False)
    op.add_column('scripts', sa.Column('script_type', sa.String(length=30), server_default='mystery', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'script_type')
    op.drop_index(op.f('ix_generation_tasks_status'), table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_draft_id'), table_name='generation_tasks')
    op.create_index(op.f('idx_generation_tasks_status'), 'generation_tasks', ['status'], unique=False)
    op.create_index(op.f('idx_generation_tasks_draft_id'), 'generation_tasks', ['draft_id'], unique=False)
    op.drop_index(op.f('ix_generation_task_events_task_id'), table_name='generation_task_events')
    op.create_index(op.f('idx_generation_task_events_task_id'), 'generation_task_events', ['task_id'], unique=False)
    # ### end Alembic commands ###
