"""game_sessions_fk_to_world_characters

Revision ID: a21226f5c969
Revises: 01f437c7c05d
Create Date: 2026-04-09 08:57:54.841091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a21226f5c969'
down_revision: Union[str, Sequence[str], None] = '01f437c7c05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('game_sessions_character_id_fkey'), 'game_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'game_sessions', 'world_characters', ['character_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('game_sessions_character_id_fkey'), 'game_sessions', 'characters', ['character_id'], ['id'])
    # ### end Alembic commands ###
